### ISSUE TITLE
Failed building wheel for minorminer

### ISSUE THREAD

**Issue by Epulsar** [dwavesystems/minorminer#47] opened 2018-06-18 22:10 UTC
I am installing the various Dwave python modules on a Macintosh desktop, and I cannot import all of the various modules because some of them require the successful installation of minor miner - and this is the error code I am getting.

Running setup.py bdist_wheel for minorminer ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-wheel-zsdxpejp --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'minorminer' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/python
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I -I./include/ -I/anaconda3/include/python3.6m -c ./python/minorminer.cpp -o build/temp.macosx-10.7-x86_64-3.6/./python/minorminer.o -std=c++11 -Wextra -Wno-format-security -Ofast -fomit-frame-pointer -DNDEBUG -fno-rtti
  ./python/minorminer.cpp:567:10: fatal error: 'random' file not found
  #include <random>
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for minorminer
  Running setup.py clean for minorminer
Failed to build minorminer
Installing collected packages: minorminer, dwave-system
  Running setup.py install for minorminer ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-record-ibwn_rc6/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'minorminer' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/python
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I -I./include/ -I/anaconda3/include/python3.6m -c ./python/minorminer.cpp -o build/temp.macosx-10.7-x86_64-3.6/./python/minorminer.o -std=c++11 -Wextra -Wno-format-security -Ofast -fomit-frame-pointer -DNDEBUG -fno-rtti
    ./python/minorminer.cpp:567:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-record-ibwn_rc6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/

**Comment by bellert** [comment] 2018-06-18 22:13
Duplicate of #46

**Comment by Epulsar** [comment] 2018-06-18 22:16
Ah yes that is true - I did not see that.

**Comment by bellert** [comment] 2018-06-18 22:19
Can you give me a few more lines earlier in the traceback? Everything after
```
Running setup.py install for minorminer ... error
```

**Comment by Epulsar** [comment] 2018-06-18 22:21
Running setup.py bdist_wheel for minorminer ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-wheel-zsdxpejp --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'minorminer' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/python
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I -I./include/ -I/anaconda3/include/python3.6m -c ./python/minorminer.cpp -o build/temp.macosx-10.7-x86_64-3.6/./python/minorminer.o -std=c++11 -Wextra -Wno-format-security -Ofast -fomit-frame-pointer -DNDEBUG -fno-rtti
  ./python/minorminer.cpp:567:10: fatal error: 'random' file not found
  #include <random>
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for minorminer
  Running setup.py clean for minorminer
Failed to build minorminer
Installing collected packages: minorminer, dwave-system
  Running setup.py install for minorminer ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-record-ibwn_rc6/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'minorminer' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/python
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I -I./include/ -I/anaconda3/include/python3.6m -c ./python/minorminer.cpp -o build/temp.macosx-10.7-x86_64-3.6/./python/minorminer.o -std=c++11 -Wextra -Wno-format-security -Ofast -fomit-frame-pointer -DNDEBUG -fno-rtti
    ./python/minorminer.cpp:567:10: fatal error: 'random' file not found
    #include <random>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-record-ibwn_rc6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kd/_t0h2d2j2_n15w7v74w5pv800000gv/T/pip-install-vq3jy6k4/minorminer/

**Closed as completed** 2018-06-21 00:34 UTC

**Comment by Abdullahjavednesar** [comment] 2022-02-27 07:06
Hi @bellert,

I am still facing this issue. https://github.com/dwavesystems/dwave-system/issues/375#issuecomment-1052415326
Can you please help!
