### ISSUE TITLE
chains for disconnected nodes

### ISSUE THREAD

**Issue by pau557** [dwavesystems/minorminer#129] opened 2020-06-04 22:42 UTC
**Description**
I am embedding a `dimod.BQM`s into a D-Wave processor. For this, I use a `dwave.system.FixedEmbeddingComposite` and an embedding found by `minorminer`. However, I find that if the bqm has disconnected nodes, the embedding won't contain a mapping for them. This raises a `MissingChainError` from the composite.

**To Reproduce**
Short example:
```
In [2]: import networkx as nx
In [3]: import minorminer
In [4]: import dimod
In [5]: target_graph = nx.complete_graph(100)
In [6]: bqm = dimod.BQM.from_ising({0:1}, {(1,2):2})
In [7]: source_graph = nx.Graph()
In [8]: source_graph.add_edges_from(bqm.quadratic)
In [9]: source_graph.add_nodes_from(bqm.linear)
In [10]: emb = minorminer.find_embedding(source_graph, target_graph)
In [11]: emb
Out[11]: {1: [58], 2: [35]}
# node 0 is missing
```

**Expected behavior**
Minorminer returning a mapping for each logical variable in the source graph.

**Environment:**
 - OS: MacOS 10.14.6
 - Python version: 3.7.0
- Minorminer: 0.1.9 

**Additional context**

More context
```
In [1]: import dimod
In [2]: import dwave_networkx as dnx
In [3]: from dwave.system import DWaveSampler
In [4]: bqm = dimod.BQM.from_ising({0:1}, {(1,2):2})
In [5]: sampler = DWaveSampler(qpu=True)
In [6]: sampler.properties['topology']
Out[6]: {'type': 'chimera', 'shape': [16, 16, 4]}
In [7]: target_graph = dnx.chimera_graph(16, edge_list=sampler.edgelist)
In [8]: import networkx as nx
In [9]: source_graph = nx.Graph()
In [10]: source_graph.add_edges_from(bqm.quadratic)
In [11]:  source_graph.add_nodes_from(bqm.linear)
In [13]: import minorminer
In [14]: emb = minorminer.find_embedding(source_graph, target_graph)
In [15]: from dwave.system import FixedEmbeddingComposite
In [16]: fec_sampler.sample(bqm)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-1b336bb49999> in <module>()
----> 1 fec_sampler.sample(bqm)

NameError: name 'fec_sampler' is not defined

In [17]: fec_sampler = FixedEmbeddingComposite(sampler, emb)

In [18]: fec_sampler.sample(bqm)
---------------------------------------------------------------------------
MissingChainError                         Traceback (most recent call last)
<ipython-input-18-1b336bb49999> in <module>()
----> 1 fec_sampler.sample(bqm)

/anaconda3/lib/python3.7/site-packages/dwave/system/composites/embedding.py in sample(self, bqm, **parameters)
    469             self._fix_embedding(embedding)
    470 
--> 471         return super(LazyFixedEmbeddingComposite, self).sample(bqm, **parameters)
    472 
    473 

/anaconda3/lib/python3.7/site-packages/dwave/system/composites/embedding.py in sample(self, bqm, chain_strength, chain_break_method, chain_break_fraction, embedding_parameters, return_embedding, warnings, **parameters)
    236         bqm_embedded = embed_bqm(bqm, embedding, target_adjacency,
    237                                  chain_strength=chain_strength,
--> 238                                  smear_vartype=dimod.SPIN)
    239 
    240         if 'initial_state' in parameters:

/anaconda3/lib/python3.7/site-packages/dwave/embedding/transforms.py in embed_bqm(source_bqm, embedding, target_adjacency, chain_strength, smear_vartype)
    112             chain = embedding[v]
    113         else:
--> 114             raise MissingChainError(v)
    115 
    116         if any(u not in target_adjacency for u in chain):

MissingChainError: chain for 0 is empty or not contained in this embedding


```

**Comment by boothby** [comment] 2020-06-05 16:08
duplicate of #126

**Closed as completed by boothby** 2020-06-05 16:08 UTC
