### ISSUE TITLE
memory corruption in find_embedding() with fixed_chains option

### ISSUE THREAD

**Issue by singhrohitip** [dwavesystems/minorminer#91] opened 2019-10-28 08:41 UTC
**Description**
I bumped into an error when I tried to call _minorminer.find_embedding()_ with fixed_chain option. I have uploaded my code as a text file.

**To Reproduce**
Download the reprod.txt. (actually its a python file), put in your developer token (I removed mine on purpose) and just run the file.

**Expected behavior**
I don't expect it to crash. It runs fine if I provide other fixed_chains.

**Environment:**
 - Red Hat Enterprise Linux Server release 7.7 (Maipo)
 - Python version: [3.7.1]
 - latest dwave tools

**Additional context**
[reprod.txt](https://github.com/dwavesystems/minorminer/files/3777605/reprod.txt)

**Comment by boothby** [comment] 2019-10-28 20:18
Thanks for your report!  I've further isolated the issue down to a very short minimal working example, which will be tested for all future versions of minorminer.  The issue is fixed on my ~~local machine~~ repo and we'll have a new version out this week.

**Closed as completed** 2019-10-29 17:19 UTC
